## Assignment: work with numpy


### Jitendra Sanjay Bhavsar

In [26]:
import numpy as np   # import numpy library 



# Work with numpy array 

In [27]:
a=np.array([2,2,2,2])
print(a)
print(np.dtype)               # array type
print(a.dtype)                # Datatype of items
print(a.ndim)                 # dimensions type

[2 2 2 2]
<class 'numpy.dtype'>
int32
1


In [28]:
a=np.array([2.3,2.5,2,2])     # Datatype of items
print(a.dtype)

float64


In [29]:
a=np.array(["2",2,2,2])     
print(a.dtype)     # In numpy array if we take one items in double quote and another is int then data type is unic code (string)

<U11


In [30]:
a=np.array([[1,2,3,4,5,6]])
print(a.ndim)

2


In [31]:
a=np.array([[[1,2,3,4,5,6]]])
print(a)
print(a.ndim)

[[[1 2 3 4 5 6]]]
3


In [32]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


In [33]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [34]:
a=np.array([[[1,2],[3,4],[5,6]]])
print(a)
print(a.ndim)        # Number of dimensions

[[[1 2]
  [3 4]
  [5 6]]]
3


In [35]:
a=np.array([[[[1,2],[3,4],[5,6]]]])
print(a)
print(a.ndim)

[[[[1 2]
   [3 4]
   [5 6]]]]
4


In [36]:
a=np.array([50])  # One dimension array
print(a)
print(a.ndim)

[50]
1


In [37]:
a=np.array(50) #Zero Dimension array
print(a)
print(a.ndim)  

50
0


In [38]:
a=np.array([[[1,2,3,4],[5,6,7,8]]])
print(a)
print(a.ndim)
print(a.shape)   # Here we get Number of dim, number of rows and number of columns

[[[1 2 3 4]
  [5 6 7 8]]]
3
(1, 2, 4)


In [39]:
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(a)
print(a.ndim)
print(a.shape)   # Here we get Number of dim, number of rows and number of columns

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3
(1, 3, 4)


In [40]:
a=np.array([[[1,2,3,4]],[[9,10,11,12]],[[5,6,7,8]]])
print(a)
print(a.ndim)
print(np.shape(a))   # Here we get Number of dim, number of rows and number of columns

[[[ 1  2  3  4]]

 [[ 9 10 11 12]]

 [[ 5  6  7  8]]]
3
(3, 1, 4)


# Creating Array

In [41]:
ab=np.zeros([2,3])   # Creating zeros matrix
print(ab)

[[0. 0. 0.]
 [0. 0. 0.]]


In [42]:
ab=np.ones([4,4])    # Creating Ones Matrix
print(ab)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [43]:
ab=np.eye(4,4)    # Creating Ones Matrix
print(ab)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Reshape

In [44]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [45]:
b=a.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b1=(a.reshape(6,2))
print(b1)
b2=(a.reshape(2,6))
print(b2)
b3=(a.reshape(4,3))
print(b3)
b4=(a.reshape(3,4))
print(b4)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print(a.reshape(3,6))


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [48]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print(a.reshape(3,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


# working With Array slicing

In [49]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print(a[:3])

[1 2 3]


In [50]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print(a[4:])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [51]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print(a[:])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [52]:
a=np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])
print(a[0])

[1 2 3 4 5 6 7 8 9]


In [53]:
print(a[1])

[10 11 12 13 14 15 16 17 18]


In [54]:
print(a)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


In [55]:
print(a[0,:3])

[1 2 3]


In [56]:
print(a[1,:])

[10 11 12 13 14 15 16 17 18]


In [57]:
ab=(a[-1,:3])
print(ab)
for x in ab:
    print(x)

[10 11 12]
10
11
12


In [58]:
a=np.array([[[1,2,3,4],[5,6,7,8]]])
print(a)
ab=a[0,1,1]           # Here 3 Dimensional Array in which slicing is work with 3 parameter
print(ab)

[[[1 2 3 4]
  [5 6 7 8]]]
6


In [59]:
a=np.array([[[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]],[[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]])
print(a)
print("The number of dimensions is:",a.ndim)
ab=a[-1,-1,0,:2]
print(ab)

[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]]]
The number of dimensions is: 4
[ 9 10]


# Working with array Spliting 

In [60]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
ab=(np.array_split(a,4))
print(ab)


[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14]), array([15, 16, 17, 18])]


In [61]:
print(ab[2])

[11 12 13 14]


In [62]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
ab=np.array_split(a,6)
print(ab)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12]), array([13, 14, 15]), array([16, 17, 18])]


In [63]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
ab=np.array_split(a,22)
ab

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([11]),
 array([12]),
 array([13]),
 array([14]),
 array([15]),
 array([16]),
 array([17]),
 array([18]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32)]